PREFIX ?= ${HOME}/bin

GITIGNORE_RULES = python,linux,windows,osx
PY_FILES = jrep

# General rules

all: test

install: test
	cp jrep ${PREFIX}

test: test.pep8 test.pylint

test.pep8:
	@ python -m pep8 $(PY_FILES)

test.pylint:
	@ python -m pylint --errors-only $(PY_FILES)

autofmt:
	@ python -m autopep8 -i $(PY_FILES)

clean:
	find . -name "*.pyc" -type f -delete
	find . -name "__pycache__" -type d -delete

# Guts

# .PHONY rule hints make that these rules don't produce result files
.PHONY: all install test test.pep8 test.pylint autofmt clean

.gitignore: .gitignore.local
	@ rm -f .gitignore
	@ echo "# AUTOGENERATED - WILL BE OVERWRITTEN" > .gitignore
	@ echo "# edit .gitignore.local and run make .gitignore" >> .gitignore
	@ echo >> .gitignore
	@ cat .gitignore.local >> .gitignore
	@ echo >> .gitignore
	@ echo '#' https://www.gitignore.io/api/$(GITIGNORE_RULES) >> .gitignore
	@ curl     https://www.gitignore.io/api/$(GITIGNORE_RULES) >> .gitignore
